#!/bin/bash

myfping=`which fping`
if [ -z ${myfping} ]; then
  echo "Fping not locate on your system.  Please install fping"
fi

myfping6=`which fping6`
if [ -z ${myfping6} ]; then
  echo "Fping6 is not located on your system.  Please install fping6"
fi

fping_v4 () {
  ${myfping} -c 3 -sq  ${1} 2>&1 | sed 's/\([0-9]*\)\/\([0-9]*\)\/\([0-9]\)%/xmt=\1 rcv=\2 loss=\3/;s/\([0-9]*.[0-9]*\)\/\([0-9].*\)\/\([0-9].*\)/min=\1 avg=\2 max=\3/' | sed -r '/targets/,/real time/d;s/[0-9]*.[0-9]*.[0-9]*.[0-9]* : xmt\/rcv\/%loss = /PING OK|/;s/, min\/avg\/max = / /'
}
fping_v6 () {
  ${myfping6} -c 3 -q ${1} 2>&1 | sed 's/\([0-9]*\)\/\([0-9]*\)\/\([0-9]\)%/xmt=\1 rcv=\2 loss=\3/;s/\([0-9]*.[0-9]*\)\/\([0-9].*\)\/\([0-9].*\)/min=\1 avg=\2 max=\3/' | sed -r '/targets/,/real time/d;s/(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])) : xmt\/rcv\/%loss = /PING OK|/;s/, min\/avg\/max = / /'
}

if [[ "${1}" =~ .*:.* ]]; then
  fping_v6 ${1}
elif [[ "${1}" =~ .*\..* ]]; then
  fping_v4 ${1}
else
  echo "Can't Determine if IPv4 or IPv6 address or No address given"
fi
